_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
DATASETS:
  TRAIN: ('t4_voc_coco_2007_val_with_known_and_unk', )
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (155500, 156500)
  MAX_ITER: 50000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t4_train_with_all"
OWOD:
  ENABLE_CLUSTERING: False
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  PREV_INTRODUCED_CLS: 60
  CUR_INTRODUCED_CLS: 20
  CLUSTERING:
    START_ITER: 116500