_BASE_: "../../Base-RCNN-C4-OWOD.yaml"
MODEL:
  WEIGHTS: "/home/joseph/workspace/OWOD/output/t2/model_final.pth"
DATASETS:
  TRAIN: ('t2_voc_coco_2007_train', ) # t1_voc_coco_2007_train, t1_voc_coco_2007_ft
  TEST: ('voc_coco_2007_test', )
SOLVER:
  STEPS: (122000, 132000)
  MAX_ITER: 142000
  WARMUP_ITERS: 0
OUTPUT_DIR: "./output/t2"
OWOD:
  PREV_INTRODUCED_CLS: 20
  CUR_INTRODUCED_CLS: 20
  ENABLE_THRESHOLD_AUTOLABEL_UNK: False
  ENABLE_CLUSTERING: False