_BASE_: "../../../Base-RCNN-C4-OWOD.yaml"
MODEL:
#  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  WEIGHTS: "/home/fk1/workspace/OWOD/output/iOD/19_p_1/model_0009999.pth"
  ROI_HEADS:
    #    NUM_CLASSES: 21 # 0-19 Known class; 20 -> Unknown; 21 -> Background.
    NUM_CLASSES: 21
  ROI_BOX_HEAD:
    CLS_AGNOSTIC_BBOX_REG: True
DATASETS:
  TRAIN: ('voc_2007_trainval', )
  TEST: ('voc_2007_test', )
SOLVER:
  STEPS: (22000, 24000)
  MAX_ITER: 20000
  WARMUP_ITERS: 100
OUTPUT_DIR: "./output/iOD/19_p_1"
OWOD:
  ENABLE_THRESHOLD_AUTOLABEL_UNK: True
  ENABLE_CLUSTERING: False
  PREV_INTRODUCED_CLS: 19
  CUR_INTRODUCED_CLS: 1
  CLUSTERING:
    START_ITER: 20000
    UPDATE_MU_ITER: 3100
SEED: 9999